  var WOMT_aParteienBeschreibung                 = new Array();
  var WOMT_aParteienBeschreibungChecksum         = new Array();
  var WOMT_sGenerationTimeParteienBeschreibung   = '';
  

/*
  --------------------------------------------------------------
  Vordefinieren der in den Templates gefunden assoziativen Keys
  mit denenen auf WOMT_aTexte und WOMT_aBilder zugriffen wird
  nicht vorhanden Indexe fuehren in Javascript sonst zu Fehlern!

  Wenn mit Variablen auf die assoziativen Arrays zugegriffen wird
  kann dies nicht automatisch analsysit werden,
  die Variablen werden aber zur Erinnuner im output angezeigt!
  --------------------------------------------------------------
*/
WOMT_aParteienBeschreibung[0]=new Array();
WOMT_aParteienBeschreibung[1]=new Array();
WOMT_aParteienBeschreibung[2]=new Array();
WOMT_aParteienBeschreibung[3]=new Array();
WOMT_aParteienBeschreibung[4]=new Array();
WOMT_aParteienBeschreibung[5]=new Array();
WOMT_aParteienBeschreibung[6]=new Array();
WOMT_aParteienBeschreibung[7]=new Array();
WOMT_aParteienBeschreibung[8]=new Array();
WOMT_aParteienBeschreibung[9]=new Array();
WOMT_aParteienBeschreibung[10]=new Array();
WOMT_aParteienBeschreibung[11]=new Array();
WOMT_aParteienBeschreibung[12]=new Array();
WOMT_aParteienBeschreibung[0][0]='Die CDU hat christlich-soziale, liberale und konservative Wurzeln. Sie sieht sich als Partei für Stabilität, Wohlstand, Sicherheit und Wachstum. In ihrem Wahlprogramm stellt sie u.a. die Familie in den Fokus, eine gute Gesundheitsversorgung und Verbraucherschutz. Sie ist die größte Oppositionspartei im Landtag.';
WOMT_aParteienBeschreibung[0][1]='Die CDU hat christlich-soziale, liberale und konservative Wurzeln. Sie sieht sich als Partei für Stabilität, Wohlstand, Sicherheit und Wachstum. In ihrem Wahlprogramm stellt sie u.a. die Familie in den Fokus, eine gute Gesundheitsversorgung und Verbraucherschutz. Sie ist die größte Oppositionspartei im Landtag.';
WOMT_aParteienBeschreibung[0][2]='Die CDU hat christlich-soziale, liberale und konservative Wurzeln. Sie sieht sich als Partei für Stabilität, Wohlstand, Sicherheit und Wachstum. In ihrem Wahlprogramm stellt sie u.a. die Familie in den Fokus, eine gute Gesundheitsversorgung und Verbraucherschutz. Sie ist die größte Oppositionspartei im Landtag.';
WOMT_aParteienBeschreibung[1][0]='Die Grundwerte der SPD sind Freiheit, Gerechtigkeit und Solidarität, wobei die schleswig-holsteinischen Sozialdemokraten als eher linker Landesverband gelten. Die SPD will u.a. mehr in Bildung und Infrastruktur investieren und ab 2018 keine neuen Schulden machen. Sie stellt zusammen mit Bündnis 90/Die Grünen und SSW die Regierung.';
WOMT_aParteienBeschreibung[1][1]='Die Grundwerte der SPD sind Freiheit, Gerechtigkeit und Solidarität, wobei die schleswig-holsteinischen Sozialdemokraten als eher linker Landesverband gelten. Die SPD will u.a. mehr in Bildung und Infrastruktur investieren und ab 2018 keine neuen Schulden machen. Sie stellt zusammen mit Bündnis 90/Die Grünen und SSW die Regierung.';
WOMT_aParteienBeschreibung[1][2]='Die Grundwerte der SPD sind Freiheit, Gerechtigkeit und Solidarität, wobei die schleswig-holsteinischen Sozialdemokraten als eher linker Landesverband gelten. Die SPD will u.a. mehr in Bildung und Infrastruktur investieren und ab 2018 keine neuen Schulden machen. Sie stellt zusammen mit Bündnis 90/Die Grünen und SSW die Regierung.';
WOMT_aParteienBeschreibung[2][0]='Der schleswig-holsteinische Landesverband der GRÜNEN wurde 1980 gegründet. Die GRÜNEN bilden zurzeit mit SPD und SSW die Regierung. Die Partei beansprucht für sich, eine ökologische, gerechte und weltoffene Politik zu vertreten. Schwerpunkte des Wahlprogramms sind Natur- und Umweltschutz, der Ausbau des ÖPNV und die Förderung von Kindern.';
WOMT_aParteienBeschreibung[2][1]='Der schleswig-holsteinische Landesverband der GRÜNEN wurde 1980 gegründet. Die GRÜNEN bilden zurzeit mit SPD und SSW die Regierung. Die Partei beansprucht für sich, eine ökologische, gerechte und weltoffene Politik zu vertreten. Schwerpunkte des Wahlprogramms sind Natur- und Umweltschutz, der Ausbau des ÖPNV und die Förderung von Kindern.';
WOMT_aParteienBeschreibung[2][2]='Der schleswig-holsteinische Landesverband der GRÜNEN wurde 1980 gegründet. Die GRÜNEN bilden zurzeit mit SPD und SSW die Regierung. Die Partei beansprucht für sich, eine ökologische, gerechte und weltoffene Politik zu vertreten. Schwerpunkte des Wahlprogramms sind Natur- und Umweltschutz, der Ausbau des ÖPNV und die Förderung von Kindern.';
WOMT_aParteienBeschreibung[3][0]='Die FDP versteht sich als Partei der Marktwirtschaft, der Eigenverantwortung und des Wettbewerbs. Ihr besonderes Augenmerk gilt der Idee der individuellen Freiheit. In ihrem Wahlprogramm setzt die Partei einen Schwerpunkt auf die Bildungspolitik und will die mittelständische Wirtschaft stärker unterstützen.';
WOMT_aParteienBeschreibung[3][1]='Die FDP versteht sich als Partei der Marktwirtschaft, der Eigenverantwortung und des Wettbewerbs. Ihr besonderes Augenmerk gilt der Idee der individuellen Freiheit. In ihrem Wahlprogramm setzt die Partei einen Schwerpunkt auf die Bildungspolitik und will die mittelständische Wirtschaft stärker unterstützen.';
WOMT_aParteienBeschreibung[3][2]='Die FDP versteht sich als Partei der Marktwirtschaft, der Eigenverantwortung und des Wettbewerbs. Ihr besonderes Augenmerk gilt der Idee der individuellen Freiheit. In ihrem Wahlprogramm setzt die Partei einen Schwerpunkt auf die Bildungspolitik und will die mittelständische Wirtschaft stärker unterstützen.';
WOMT_aParteienBeschreibung[4][0]='Die PIRATEN verstehen sich als "Partei der Informationsgesellschaft", welche die Ziele Transparenz, Bürgerbeteiligung und Bildung verfolgt. Seit der letzten Landtagswahl sind sie im Parlament von Schleswig-Holstein vertreten.';
WOMT_aParteienBeschreibung[4][1]='Die PIRATEN verstehen sich als "Partei der Informationsgesellschaft", welche die Ziele Transparenz, Bürgerbeteiligung und Bildung verfolgt. Seit der letzten Landtagswahl sind sie im Parlament von Schleswig-Holstein vertreten.';
WOMT_aParteienBeschreibung[4][2]='Die PIRATEN verstehen sich als "Partei der Informationsgesellschaft", welche die Ziele Transparenz, Bürgerbeteiligung und Bildung verfolgt. Seit der letzten Landtagswahl sind sie im Parlament von Schleswig-Holstein vertreten.';
WOMT_aParteienBeschreibung[5][0]='Der SSW ist 1948 als politische Interessenvertretung der dänischen Minderheit im Landesteil Schleswig und der nationalen Friesen gegründet worden. Er ist von der Sperrklausel befreit und war fast immer im Landtag vertreten.';
WOMT_aParteienBeschreibung[5][1]='Der SSW ist 1948 als politische Interessenvertretung der dänischen Minderheit im Landesteil Schleswig und der nationalen Friesen gegründet worden. Er ist von der Sperrklausel befreit und war fast immer im Landtag vertreten.';
WOMT_aParteienBeschreibung[5][2]='Der SSW ist 1948 als politische Interessenvertretung der dänischen Minderheit im Landesteil Schleswig und der nationalen Friesen gegründet worden. Er ist von der Sperrklausel befreit und war fast immer im Landtag vertreten.';
WOMT_aParteienBeschreibung[6][0]='DIE LINKE ist durch die Verschmelzung der Linkspartei.PDS und der WASG entstanden. Sie fordert einen umfassenden Ausbau des Sozialstaates, einen Mindestlohn von 12 Euro und eine Mindestrente. Zudem setzt sie sich für das Grundrecht auf Asyl ein und fordert einen konsequenten Abschiebestopp.';
WOMT_aParteienBeschreibung[6][1]='DIE LINKE ist durch die Verschmelzung der Linkspartei.PDS und der WASG entstanden. Sie fordert einen umfassenden Ausbau des Sozialstaates, einen Mindestlohn von 12 Euro und eine Mindestrente. Zudem setzt sie sich für das Grundrecht auf Asyl ein und fordert einen konsequenten Abschiebestopp.';
WOMT_aParteienBeschreibung[6][2]='DIE LINKE ist durch die Verschmelzung der Linkspartei.PDS und der WASG entstanden. Sie fordert einen umfassenden Ausbau des Sozialstaates, einen Mindestlohn von 12 Euro und eine Mindestrente. Zudem setzt sie sich für das Grundrecht auf Asyl ein und fordert einen konsequenten Abschiebestopp.';
WOMT_aParteienBeschreibung[7][0]='Die FAMILIE versteht sich als Interessenvertretung der Familien und Menschen mit Kindern. Sie stellt die Sicherung eines nachhaltigen Generationenvertrages in den Mittelpunkt ihres Programms. In Schleswig-Holstein gibt es seit 1999 einen Landesverband.';
WOMT_aParteienBeschreibung[7][1]='Die FAMILIE versteht sich als Interessenvertretung der Familien und Menschen mit Kindern. Sie stellt die Sicherung eines nachhaltigen Generationenvertrages in den Mittelpunkt ihres Programms. In Schleswig-Holstein gibt es seit 1999 einen Landesverband.';
WOMT_aParteienBeschreibung[7][2]='Die FAMILIE versteht sich als Interessenvertretung der Familien und Menschen mit Kindern. Sie stellt die Sicherung eines nachhaltigen Generationenvertrages in den Mittelpunkt ihres Programms. In Schleswig-Holstein gibt es seit 1999 einen Landesverband.';
WOMT_aParteienBeschreibung[8][0]='Die FREIEN WÄHLER verstehen sich als eine Alternative zu den etablierten Parteien. Sie wollen die kommunale Selbstverwaltung stärken, eine bessere Finanzausstattung der Gemeinden und mehr Bürgerbeteiligung. Sie haben Mitglieder in mehreren Kreistagen, verfehlten bislang aber den Einzug in das Landesparlament.';
WOMT_aParteienBeschreibung[8][1]='Die FREIEN WÄHLER verstehen sich als eine Alternative zu den etablierten Parteien. Sie wollen die kommunale Selbstverwaltung stärken, eine bessere Finanzausstattung der Gemeinden und mehr Bürgerbeteiligung. Sie haben Mitglieder in mehreren Kreistagen, verfehlten bislang aber den Einzug in das Landesparlament.';
WOMT_aParteienBeschreibung[8][2]='Die FREIEN WÄHLER verstehen sich als eine Alternative zu den etablierten Parteien. Sie wollen die kommunale Selbstverwaltung stärken, eine bessere Finanzausstattung der Gemeinden und mehr Bürgerbeteiligung. Sie haben Mitglieder in mehreren Kreistagen, verfehlten bislang aber den Einzug in das Landesparlament.';
WOMT_aParteienBeschreibung[9][0]='Die AfD wurde 2013 gegründet und anfangs vor allem als "Anti-Euro-Partei" wahrgenommen. 2015 gewann der rechtspopulistische Flügel der AfD an Gewicht. Zur Wahl fordert die Partei u.a. die Stärkung des Leistungsprinzips in der Schule, den Ausstieg aus der Energiewende und die Reduzierung der Krankenkassenleistungen auf die Absicherung "hoher Risiken".';
WOMT_aParteienBeschreibung[9][1]='Die AfD wurde 2013 gegründet und anfangs vor allem als "Anti-Euro-Partei" wahrgenommen. 2015 gewann der rechtspopulistische Flügel der AfD an Gewicht. Zur Wahl fordert die Partei u.a. die Stärkung des Leistungsprinzips in der Schule, den Ausstieg aus der Energiewende und die Reduzierung der Krankenkassenleistungen auf die Absicherung "hoher Risiken".';
WOMT_aParteienBeschreibung[9][2]='Die AfD wurde 2013 gegründet und anfangs vor allem als "Anti-Euro-Partei" wahrgenommen. 2015 gewann der rechtspopulistische Flügel der AfD an Gewicht. Zur Wahl fordert die Partei u.a. die Stärkung des Leistungsprinzips in der Schule, den Ausstieg aus der Energiewende und die Reduzierung der Krankenkassenleistungen auf die Absicherung "hoher Risiken".';
WOMT_aParteienBeschreibung[10][0]='Die LKR wurde 2015 unter dem Namen ALFA vom ehemaligen AfD-Sprecher Lucke gegründet. Sie vertritt konservative und wirtschaftsliberale Positionen. Zur Landtagswahl in Schleswig-Holstein tritt sie u.a. für eine bessere Ausstattung der Polizei, größere Förderung des ländlichen Raums und für den Abbau der Landesschulden ein.';
WOMT_aParteienBeschreibung[10][1]='Die LKR wurde 2015 unter dem Namen ALFA vom ehemaligen AfD-Sprecher Lucke gegründet. Sie vertritt konservative und wirtschaftsliberale Positionen. Zur Landtagswahl in Schleswig-Holstein tritt sie u.a. für eine bessere Ausstattung der Polizei, größere Förderung des ländlichen Raums und für den Abbau der Landesschulden ein.';
WOMT_aParteienBeschreibung[10][2]='Die LKR wurde 2015 unter dem Namen ALFA vom ehemaligen AfD-Sprecher Lucke gegründet. Sie vertritt konservative und wirtschaftsliberale Positionen. Zur Landtagswahl in Schleswig-Holstein tritt sie u.a. für eine bessere Ausstattung der Polizei, größere Förderung des ländlichen Raums und für den Abbau der Landesschulden ein.';
WOMT_aParteienBeschreibung[11][0]='Die PARTEI wurde 2004 gegründet und ist inhaltlich und personell mit dem Satiremagazin Titanic verflochten. Auch ihre Forderungen zur Landtagswahl in Schleswig-Holstein haben satirischen Charakter. U.a. fordert die PARTEI, dass Tierärzte die ärztliche Versorgung auf dem Land sichern können und eine "Seehundstaffel" die militärische Sicherung des Wattenmeer übernehmen solle.';
WOMT_aParteienBeschreibung[11][1]='Die PARTEI wurde 2004 gegründet und ist inhaltlich und personell mit dem Satiremagazin Titanic verflochten. Auch ihre Forderungen zur Landtagswahl in Schleswig-Holstein haben satirischen Charakter. U.a. fordert die PARTEI, dass Tierärzte die ärztliche Versorgung auf dem Land sichern können und eine "Seehundstaffel" die militärische Sicherung des Wattenmeer übernehmen solle.';
WOMT_aParteienBeschreibung[11][2]='Die PARTEI wurde 2004 gegründet und ist inhaltlich und personell mit dem Satiremagazin Titanic verflochten. Auch ihre Forderungen zur Landtagswahl in Schleswig-Holstein haben satirischen Charakter. U.a. fordert die PARTEI, dass Tierärzte die ärztliche Versorgung auf dem Land sichern können und eine "Seehundstaffel" die militärische Sicherung des Wattenmeer übernehmen solle.';
WOMT_aParteienBeschreibung[12][0]='Die Partei Z.SH wurde im März 2017 gegründet und tritt besonders für die Sicherung der medizinischen Grundversorgung in Schleswig-Holstein ein. Zudem stellt sie die Lebens- und Arbeitsbedingungen im ländlichen Raum in den Mittelpunkt ihres Programms.';
WOMT_aParteienBeschreibung[12][1]='Die Partei Z.SH wurde im März 2017 gegründet und tritt besonders für die Sicherung der medizinischen Grundversorgung in Schleswig-Holstein ein. Zudem stellt sie die Lebens- und Arbeitsbedingungen im ländlichen Raum in den Mittelpunkt ihres Programms.';
WOMT_aParteienBeschreibung[12][2]='Die Partei Z.SH wurde im März 2017 gegründet und tritt besonders für die Sicherung der medizinischen Grundversorgung in Schleswig-Holstein ein. Zudem stellt sie die Lebens- und Arbeitsbedingungen im ländlichen Raum in den Mittelpunkt ihres Programms.';
WOMT_aParteienBeschreibungChecksum["sum"]='030f585e21ab5fcbd8c799272b731cd5';
WOMT_aParteienBeschreibungChecksum["sum2"]='2c9a2eda090d8d1df559e0ab711cb155';
WOMT_sGenerationTimeParteienBeschreibung ='07.04.2017 11:21:26';
