#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations

import argparse
import ast
import difflib
import re
import sys
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
ARCH_DOC = REPO_ROOT / "docs" / "ARCHITECTURE.md"

START_MARKER = "<!-- AUTOGEN:ARCHITECTURE_DEPS:START -->"
END_MARKER = "<!-- AUTOGEN:ARCHITECTURE_DEPS:END -->"


@dataclass(frozen=True)
class DepGraph:
    modules: dict[str, Path]  # module_name -> file path
    edges: set[tuple[str, str]]  # (src_module, dst_module)


_PKG_DIR = REPO_ROOT / "wahlomat_extended_analysis"
def _repo_modules() -> dict[str, Path]:
    """
    Repo-local top-level modules (root/*.py), excluding private helpers.
    The goal is a stable architecture map, not a full import graph of tests.
    """
    out: dict[str, Path] = {}
    for p in sorted(REPO_ROOT.glob("*.py")):
        if p.name.startswith("_"):
            continue
        # Local scratch file (explicitly ignored in .gitignore); don't include in docs graph.
        if p.name == "untitled.py":
            continue
        out[p.stem] = p
    if _PKG_DIR.is_dir():
        for p in sorted(_PKG_DIR.glob("*.py")):
            if p.stem == "__init__":
                continue
            out[f"wahlomat_extended_analysis.{p.stem}"] = p
    return out


def _parse_imports(py_path: Path) -> set[str]:
    try:
        src = py_path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        src = py_path.read_text(encoding="utf-8", errors="replace")
    tree = ast.parse(src, filename=str(py_path))
    imported: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                raw = (alias.name or "").strip()
                if not raw:
                    continue
                imported.add(raw)
                imported.add(raw.split(".", 1)[0])
        elif isinstance(node, ast.ImportFrom):
            if node.level and node.level > 0:
                # Relative imports aren't relevant for the repo-root scripts map.
                continue
            if not node.module:
                continue
            raw = node.module.strip()
            if raw:
                imported.add(raw)
                imported.add(raw.split(".", 1)[0])
    return imported


def build_dep_graph() -> DepGraph:
    mods = _repo_modules()
    edges: set[tuple[str, str]] = set()
    for src_mod, path in mods.items():
        imports = _parse_imports(path)
        for imp in imports:
            if imp in mods and imp != src_mod:
                edges.add((src_mod, imp))
    return DepGraph(modules=mods, edges=edges)


_ID_SAFE_RE = re.compile(r"[^A-Za-z0-9_]")


def _node_id(module_name: str) -> str:
    return _ID_SAFE_RE.sub("_", f"m_{module_name}")


def render_mermaid(g: DepGraph) -> str:
    lines: list[str] = []
    lines.append("```mermaid")
    lines.append("flowchart LR")

    # Nodes (stable order)
    for mod in sorted(g.modules.keys()):
        nid = _node_id(mod)
        label = str(g.modules[mod].relative_to(REPO_ROOT))
        lines.append(f'  {nid}["{label}"]')

    # Edges (stable order)
    for src, dst in sorted(g.edges):
        lines.append(f"  {_node_id(src)} --> {_node_id(dst)}")

    lines.append("```")
    return "\n".join(lines) + "\n"


def _replace_autogen_block(doc_text: str, *, mermaid_block: str) -> str:
    if START_MARKER not in doc_text or END_MARKER not in doc_text:
        raise ValueError(
            f"Missing markers in {ARCH_DOC}: expected {START_MARKER} ... {END_MARKER}"
        )
    pre, rest = doc_text.split(START_MARKER, 1)
    _, post = rest.split(END_MARKER, 1)

    block = (
        f"{START_MARKER}\n"
        "<!-- This block is generated by tools/gen_architecture.py. Do not edit by hand. -->\n"
        f"{mermaid_block}"
        f"{END_MARKER}"
    )
    # Preserve exactly one blank line after the end marker if there was one.
    if post.startswith("\n\n"):
        return pre + block + post
    if post.startswith("\n"):
        return pre + block + post
    return pre + block + "\n" + post


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Generate docs/ARCHITECTURE.md dependency graph block.")
    ap.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if docs/ARCHITECTURE.md would change.",
    )
    args = ap.parse_args(argv)

    doc_before = ARCH_DOC.read_text(encoding="utf-8")
    g = build_dep_graph()
    mermaid = render_mermaid(g)
    doc_after = _replace_autogen_block(doc_before, mermaid_block=mermaid)

    if args.check:
        if doc_after != doc_before:
            diff = difflib.unified_diff(
                doc_before.splitlines(True),
                doc_after.splitlines(True),
                fromfile=str(ARCH_DOC),
                tofile=str(ARCH_DOC),
            )
            sys.stderr.write("docs/ARCHITECTURE.md is out of date. Run:\n")
            sys.stderr.write("  python tools/gen_architecture.py\n\n")
            sys.stderr.writelines(diff)
            return 1
        return 0

    if doc_after != doc_before:
        ARCH_DOC.write_text(doc_after, encoding="utf-8")
        print(f"Updated: {ARCH_DOC}")
    else:
        print(f"Up to date: {ARCH_DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

